version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: >
      sh -c "python src/manage.py wait_for_db &&
      python src/manage.py migrate &&
      python src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - web-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  web-db-data:
