version: "3.9"

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    environment:
      - DB_HOST=db
    env_file: .env
    container_name: ${CONTAINER_NAME}
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      uwsgi --ini docker/uwsgi.ini"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - web-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  web-db-data:
